### PR TITLE
Player lockout on !call and other various improvements to !call

### LINKED ISSUE #469: !callset improvements
As of now, only `!call` is counted when doing a greater than 1 callset. This should be changed to include other calls in general. Also, a command (perhaps `!callcount`) could be made to see how many people have used any type of call. Lastly, a line should be added that says "2 of 2 calls reached, calling command." or something of the sort. 

I fully intent to do this later in the week, but I'd like other ideas and suggestions for the system.

### PR DESCRIPTION
**Pull request by MrPeanut1028**
1. Any type of `!call` command now counts for the total number of calls
2. Players can now only send one call at a time
3. `!callcount` added to state the number of calls that have been sent
4. `!callplayers` added to see who has already sent `!call`
5. Maximum of 10 callers now set in stone
6. Added some additional lines explaining if / why a command was / was not sent

This adds all of the features in (fixes #469 )

### CODE REVIEW

**Comment by MrPeanut1028** [comment]
@KingBranBran we did it again

**Comment by KingBranBran** [comment]
Oof

**Comment by sleepin-fang** [comment]
Big oof

**Comment by samfun123** [comment]
Closed by 471

**Pull request closed without merging**
