### PR TITLE
Add VSMode Auto Team Assigning

### PR DESCRIPTION
**Pull request by MrPeanut1028**
This includes better auto-balancing features for VSMode. This also includes a competitive option when a percentage of the best players will be pitted against the others.

### CODE REVIEW

**Comment by red031000** [comment]
I am extremely confused about the choice of some of this implementation

**Comment by red031000** [comment]
I added in an activity tracker and a team tracker specifically *for* this, the idea was going to be that the teams would auto-balance based on who's actively playing atm, and not just who *has* played during the session

**Comment by red031000** [comment]
I'm also unsure why you decided to have separate arrays based on rank but do the same thing with them anyway

**Comment by red031000** [comment]
also calling Keys.Add() seems very very wrong, and should throw a NotSupportedException, I'm unsure what you're trying to achieve here, if you want to convert to an array you could always call .ToArray

**Comment by MrPeanut1028** [comment]
My goal with this PR was to separate people automatically by rank (more or less). I'm also unsure about that Keys.Add() thing, as I'm not the most familiar with Dictionaries. With that specifically, I wanted to take all of the strings and add them to their specific array. Now that I look at it, the three separate arrays are pretty pointless, so I'll end up changing that to just one.

**Comment by MrPeanut1028** [comment]
I've now made those changes you're said. Let me know if there's anything else that won't work. I added this to also assign teams randomly and at the start of every bomb, and add that mode where the top 35% (or whatever works after some testing) plays against everyone else.

**Comment by MrPeanut1028** [comment]
I've changed two more things: 
1.) The default is now the normal form of VSMode. 
2.) Players can be "Locked Out" from playing once a bomb has started, which fits better with the new form.

**Comment by red031000** [comment]
I think it looks good now

**Pull request merged**
