### PR TITLE
further cleanups

### PR DESCRIPTION
**Pull request by red031000**

### CODE REVIEW

**Comment by red031000** [comment]
Yeah, but I'm currently doing it when I have the time to, so this PR is probably going to stay open for a while

**Comment by samfun123** [comment]
Why did you remove null propagation in some places?

**Comment by red031000** [comment]
null propagation bypasses lifetime checks on unity objects

**Comment by CaitSith2** [comment]
https://github.com/JetBrains/resharper-unity/wiki/Possible-unintended-bypass-of-lifetime-check-of-underlying-Unity-engine-object - (I found out about this after having installed the Unity extension for resharper.)

**Pull request closed without merging**
