### PR TITLE
lots of fixes

### PR DESCRIPTION
**Pull request by red031000**

### CODE REVIEW

**Comment by samfun123** [comment]
If you are going to fix an issue in a PR please use one of [these](https://help.github.com/articles/closing-issues-using-keywords/) keywords to close the issue.

**Comment by red031000** [comment]
okay

**Comment by red031000** [comment]
Shall l remove the disableruncommand then? I don't think I can implement a way to disable the running of all bombs

**Comment by red031000** [comment]
that should hopefully be implemented now

**Comment by CaitSith2** [comment]
Working on things so that bomb creator will respect the global disable run command.  The plan is to have bomb creator yield return the generated KMMission object instead of directly running it.

**Comment by red031000** [comment]
I've already changed the code that you added to check if the runcommand is enabled

**Comment by red031000** [comment]
that should be everything addressed

**Pull request merged**
